# This is a basic workflow to help you get started with Actions

name: Compile PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ] # on push to ausgabe*
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: k4zuki/pandocker-alpine:3.2
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: update Tex Library Manager
        run: tlmgr update --self
        
      - name: Install xpatch
        run: tlmgr install xpatch

      - name: Github Action for LaTeX
        run: latexmk src/multiversum-027.tex
            
